version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: pokescan
      POSTGRES_USER: pokescan
      POSTGRES_PASSWORD: pokescan
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
